 # This is a basic workflow that is manually triggered

name: ProgPOE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
     # list contents or directory
      - name: List contents
        run: ls
     # Compiles classes to test 
      - name: compile classes
        working-directory: ./src
        run: javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" ./ ProgPOE/ ProgPOE.java ./ ProgPOE/Login.java ./ ProgPOE/Task.java ./ ProgPOE/StartFrames.java ./ ProgPOE/TaskFrames.java "../test/ ProgPOE/LoginTest.java" "../test/ ProgPOE/TaskTest.java""../test/ProgPOE/TaskManagerTest.java""

    # list contents of src to verify that classess compiled 
      - name: List contents of src directory after compile
        working-directory: ./src/ProgPOE
        run: ls
        
        
       # copy compiled classes to test directory 
      - name : copy compiled classes to testresources directory 
        working-directory: ./src/ProgPOE
        run: cp -t  "../../test/ ProgPOE/" Login.class  ProgPOE.class Task.class StartFrames.class TaskFrames.class TaskManager.class
        
        #copy compiled tests 
      - name : copy compiled Test classes to testresources directory 
        working-directory: ./test/ ProgPOE
        run: cp -t  "../../testresources/" Login.class  ProgPOE.class LoginTest.class Task.class StartFrames.class TaskFrames.class TaskTest.class TaskManager.class TaskManagerTest.class
        
        # list contents or directory
      - name: List contents test package
        working-directory: ./test/ ProgPOE
        run: ls
        
        #run Login Class tests and output report 
      - name: run Login Class tests and create report 
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class  ProgPOE.LoginTest  
       
       #run Task Class tests and output report 
      - name: run Task Class tests and create report 
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class  ProgPOE.TaskTest 
         
       #run TaskManager Class tests and output report 
      - name: run TaskManager Class tests and create report 
        working-directory: ./test
        run: |
         ls
         java -jar  "../testresources/junit-platform-console-standalone-1.6.0.jar" -cp "." --select-class  ProgPOE.TaskManagerTest 
